plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
strict: false

keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: tags.Role
    prefix: role

compose:
  ansible_host: public_ip_address
  ansible_ssh_private_key_file: /home/mrask/.ssh/iac-key